"""initial schema

Revision ID: 73004a4a6ea8
Revises: 
Create Date: 2026-09-28 18:52:41.542682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73004a4a6ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chain_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'INACTIVE', name='bridgestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bridge_address', 'bridges', ['address'], unique=False)
    op.create_index('idx_bridge_chain_created', 'bridges', ['chain_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_bridges_address'), 'bridges', ['address'], unique=True)
    op.create_index(op.f('ix_bridges_created_at'), 'bridges', ['created_at'], unique=False)
    op.create_index(op.f('ix_bridges_id'), 'bridges', ['id'], unique=False)
    op.create_table('validators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('uptime_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validator_active', 'validators', ['is_active'], unique=False)
    op.create_index('idx_validator_address', 'validators', ['address'], unique=False)
    op.create_index('idx_validator_joined', 'validators', ['joined_at'], unique=False)
    op.create_index(op.f('ix_validators_address'), 'validators', ['address'], unique=True)
    op.create_index(op.f('ix_validators_id'), 'validators', ['id'], unique=False)
    op.create_index(op.f('ix_validators_joined_at'), 'validators', ['joined_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('bridge_id', sa.Integer(), nullable=False),
    sa.Column('source_chain', sa.String(length=50), nullable=False),
    sa.Column('destination_chain', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_bridge_created', 'transactions', ['bridge_id', 'created_at'], unique=False)
    op.create_index('idx_tx_flagged', 'transactions', ['is_flagged'], unique=False)
    op.create_index('idx_tx_hash', 'transactions', ['tx_hash'], unique=False)
    op.create_index('idx_tx_timestamp', 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_bridge_id'), 'transactions', ['bridge_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('ANOMALY', 'TIMEOUT', 'ERROR', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_created', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alert_resolved', 'alerts', ['is_resolved'], unique=False)
    op.create_index('idx_alert_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alert_transaction', 'alerts', ['transaction_id'], unique=False)
    op.create_index('idx_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_table('anomaly_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_detected', 'anomaly_detections', ['detected_at'], unique=False)
    op.create_index('idx_anomaly_severity', 'anomaly_detections', ['severity'], unique=False)
    op.create_index('idx_anomaly_transaction', 'anomaly_detections', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_detected_at'), 'anomaly_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_id'), 'anomaly_detections', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_transaction_id'), 'anomaly_detections', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_detections_transaction_id'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_id'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_detected_at'), table_name='anomaly_detections')
    op.drop_index('idx_anomaly_transaction', table_name='anomaly_detections')
    op.drop_index('idx_anomaly_severity', table_name='anomaly_detections')
    op.drop_index('idx_anomaly_detected', table_name='anomaly_detections')
    op.drop_table('anomaly_detections')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index('idx_alert_type', table_name='alerts')
    op.drop_index('idx_alert_transaction', table_name='alerts')
    op.drop_index('idx_alert_severity', table_name='alerts')
    op.drop_index('idx_alert_resolved', table_name='alerts')
    op.drop_index('idx_alert_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bridge_id'), table_name='transactions')
    op.drop_index('idx_tx_timestamp', table_name='transactions')
    op.drop_index('idx_tx_hash', table_name='transactions')
    op.drop_index('idx_tx_flagged', table_name='transactions')
    op.drop_index('idx_tx_bridge_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_validators_joined_at'), table_name='validators')
    op.drop_index(op.f('ix_validators_id'), table_name='validators')
    op.drop_index(op.f('ix_validators_address'), table_name='validators')
    op.drop_index('idx_validator_joined', table_name='validators')
    op.drop_index('idx_validator_address', table_name='validators')
    op.drop_index('idx_validator_active', table_name='validators')
    op.drop_table('validators')
    op.drop_index(op.f('ix_bridges_id'), table_name='bridges')
    op.drop_index(op.f('ix_bridges_created_at'), table_name='bridges')
    op.drop_index(op.f('ix_bridges_address'), table_name='bridges')
    op.drop_index('idx_bridge_chain_created', table_name='bridges')
    op.drop_index('idx_bridge_address', table_name='bridges')
    op.drop_table('bridges')
    # ### end Alembic commands ###
